### ISSUE TITLE
Panic handler if Worker::run panics

### ISSUE THREAD

**Issue by ghost** [sfackler/scheduled-thread-pool#10]
When a panic occurs in ```Worker::run```, it is automatically catched by ```panic::catch_unwind``` which is fine and prevents from doing something bad.

However this is done silently, which means that if a job panics, we have no clue why and where it panicked. I've got a solution which would be to add a ```Option<PanicHandler>``` which can be declared in the ```ScheduledThreadPool::new/with_name``` constructor. This handler would then be called when a panic occurs which then means that we can understand why the panic occured.

Is it a good or a bad idea ?

**Comment by sfackler** [comment]
Would the standard panic hook not be sufficient? https://doc.rust-lang.org/std/panic/fn.set_hook.html

**Comment by ghost** [comment]
I don't think this is enough if you want to be sure that the panic occured in the thread pool and not from an other caller. For instance, let imagine that I have an external thread running, and a pool of 4 threads. If all thread are running the same method, I won't be able to tell that the panic was in the thread pool or in the "external" thread (the ```PanicInfo``` only gives the location where it panicked, not who called the method that panicked).

We could use the [Location.html#method.caller](https://doc.rust-lang.org/std/panic/struct.Location.html#method.caller) method but it is not stable yet and requires a #[track_caller] annotation.

Am I clear or do you want an example ?

**Comment by sfackler** [comment]
But what do you specifically want to do with that information?

**Comment by ghost** [comment]
With the handler I would be able to "recover" a job when a panic occurs but could be recoverable (like a wrong .unwrap or equivalent for instance).

**Comment by sfackler** [comment]
If this recovery logic is specific to a certain task, then I think it'd just be easier to use catch_unwind to handle the recovery internally rather than requiring new APIs in a thread pool.

**Comment by ghost** [comment]
Yep you are probably right about the approach. Thanks for the answers ;)
