### ISSUE TITLE
Add cancel_after(Duration) to cancel a job if the pool can't treat it fast enough

### ISSUE THREAD

**Issue by ghost** [sfackler/scheduled-thread-pool#13]
Hello !

Before submiting a PR, i'm wondering if this use case would interest you to be developped. I've got a case in my app where the thread pool is adding more tasks than it is able to treat and this leads to a lot of delay.

One way to void this is to make a sync between the thread and the task, and to cancel it after an amount of time (for instance via a mpsc channel). But to my opinion this adds a lot of code and might be easier to treat directly on the pool.

My idea is to add a new method on the JobHandle struct (something like ```cancel_after(duration: Duration)```) that would be stored in an ```Option<(Duration, Instant)>```. Then when the job is triggered, we would first check if the ```instant.elapsed() < Duration```.

What do you think of that solution ?

**Comment by sfackler** [comment]
I don't think this is a feature I've ever seen on other thread pool APIs.

You could do something like this yourself by just having the task check for a timeout as soon as it starts running and exit early if so.

**Comment by ghost** [comment]
Nope i haven't seen any kind of feature like this as well :)

Yep you're right, I've changed my code to check an Instant::now().elapsed() and that is enough for my case.
