### ISSUE TITLE
Improve for FixedRate task

### ISSUE THREAD

**Issue by jiacai2050** [sfackler/scheduled-thread-pool#9]
For now, [FixedRate](https://github.com/sfackler/scheduled-thread-pool/blob/d518a2fe5c8c06de44ecd6d9f09f58c2a97f5200/src/lib.rs#L365) first execute current job then push next job to the inner queue.
```rust
            JobType::FixedRate { mut f, rate } => {
                f();
                let new_job = Job {
                    type_: JobType::FixedRate { f, rate },
                    time: job.time + rate,
                    canceled: job.canceled,
                };
                self.shared.run(new_job)
            }
```
If `f()` take longer time than rate, the next job will get triggered after `job.time + rate`, which is not fixed rate.
Maybe we can first schedule next job, and then execute `fn()`?

**Comment by sfackler** [comment]
That would allow multiple copies of the job to potentially execute in parallel, which seems like a bad thing in many use cases.

**Comment by jiacai2050** [comment]
Sound reasonable.

I check [scheduleAtFixedRate](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledThreadPoolExecutor.html#scheduleAtFixedRate-java.lang.Runnable-long-long-java.util.concurrent.TimeUnit-) in Java, maybe we can document this situation:
> If any execution of this task takes longer than its period, then subsequent executions may start late, but will not concurrently execute.
